mail:
  host: mailhog
  port: 1025

api:
  url: api_server
  port: 8000

telegram:
  host: telegram
  port: 9000

common:
  level: DEBUG

graphite:
  enabled: true
  prefix: mailing_service.
  host: 127.0.0.1
  port: 3306
  timeout: 5
